Part 4. View single photo
korotkovoleksii/LANARS-react-school pull request #9
Opened 2023-01-24 19:33 UTC by korotkovoleksii

2023-01-26 16:26 UTC, leo-frontend requested changes

2023-01-26 16:26 UTC, leo-frontend commented on src/core/App.tsx
> +// import Header from 'modules/components/Header';
Do you need this?

2023-01-26 16:26 UTC, leo-frontend commented on src/modules/components/Header/Header.tsx
> +  // eslint-disable-next-line no-console
Delete this

2023-01-26 16:26 UTC, leo-frontend commented on src/modules/components/ShowPhotosGrid/ShowPhotosGrid.tsx
> +  // ImageListItemBar,
Remove

2023-01-26 16:26 UTC, leo-frontend commented on src/modules/pages/SelectPhotos.tsx
> +            {/* <Checkbox checked={selectedPhotoId.includes(item.id)} sx={{ position: 'absolute', right: 0 }} /> */}
Remove this

2023-01-26 17:17 UTC, korotkovoleksii commented on src/core/App.tsx
> +// import Header from 'modules/components/Header';
+

2023-01-26 17:17 UTC, korotkovoleksii commented on src/modules/components/Header/Header.tsx
> +  // eslint-disable-next-line no-console
+

2023-01-26 17:17 UTC, korotkovoleksii commented on src/modules/components/ShowPhotosGrid/ShowPhotosGrid.tsx
> +  // ImageListItemBar,
+

2023-01-26 17:17 UTC, korotkovoleksii commented on src/modules/pages/SelectPhotos.tsx
> +            {/* <Checkbox checked={selectedPhotoId.includes(item.id)} sx={{ position: 'absolute', right: 0 }} /> */}
+

2023-01-30 13:16 UTC, leo-frontend approved these changes

2023-02-01 11:36 UTC, merged